picture_unload/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from picture_unloads import urls as app_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include((app_url,'picture_unloads'),
        namespace='picture_unloads')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

picture_unloads/urls.py
'''定义 picture_unloads 的 urls'''
from django.urls import path, re_path
from . import views

app_name='picture_unloads'
urlpatterns = [
    # 显示所有图片
    path('',views.Showall.as_view(),name='showall'),
    re_path(r'^picture/unload/$', views.Upload.as_view(), name='upload'),
    re_path(r'^picture/(?P<pk>\d+)$',views.Show.as_view(), name='show'),
]    

picture_unloads/models.py
from django.db import models
from datetime import date
from django.urls import reverse

class IMG(models.Model):
    img = models.ImageField(upload_to='img')
    name = models.CharField(max_length=20)
    date_added = models.DateTimeField(default=date.today)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('picture_unloads:show',args=[str(self.id)])
    

picture_unloads/views.py
from django.shortcuts import render
from django.views.generic import DetailView,ListView
from django.views.generic.edit import CreateView
from .models import IMG

class Showall(ListView):
    queryset = IMG.objects.all().order_by('-date_added')
    # ListView 默认 context_object_name = 'object_list'
    context_object_name = 'latest_picture_list'
    # 默认的 template_name = 'pic_upload/picture_list.html'
    template_name = 'img_tem/picture_list.html'
    
class Show(DetailView):
    model = IMG
    template_name = 'img_tem/picture_detail.html'
    
class Upload(CreateView):
    model = IMG
    fields = ['name', 'img']
    template_name = 'img_tem/picture_form.html'

picture_unloads/templates/img_tem/picture_detail.html
{% block content %}
<h3>{{ img.name }}</h3>

{% if img.img %}
  <P><img src="{{img.img.url}}"/></P>
{% endif %}

<p>date:{{ picture.date_added|date:'Y-m-j' }}</p>
<p><a href="{% url 'picture_unloads:showall' %}">all the picture</a></p>
  <a href="{% url 'picture_unloads:upload'%}">new</a>
{% endblock %}

picture_unloads/templates/img_tem/picture_form.html
{% block content %}
<h3>new</h3>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="sure"/>
</form>


{% endblock %}

picture_unloads/templates/img_tem/picture_list.html
{% block content %}
<h3>picture list</h3>
<ul>
{% if latest_picture_list %}
  {% for picture in latest_picture_list %}
  <li><a href="{% url 'picture_unloads:show' picture.id %}">{{ picture.name }}</a>
    -{{ picture.date_added|date:'Y-m-j' }}</li>
  {% endfor %}
{% else %}
  <li>there is no picture</li>
{% endif %}
</ul>
<p><a href="{% url 'picture_unloads:upload' %}">new photo</a></p>
{% endblock %}

picture_unloads/templates/img_tem/showing.html
{% for img in imgs %}
<img src="{{ img.img.url }}" />
{% endfor %}

picture_unloads/templates/img_tem/uploading.html
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<input type="file" name="img">
<button type="submit">上传</button>
</form>